download:
	python download.py

emerson:
	python preprocess_emerson.py
	python preprocess_lindau.py
	python process_emerson_enrichments.py

metadata:
	python generate_metadata_chu.py

cython:
	python setupclib.py build_ext --inplace
